### ISSUE TITLE
When I type "npm run dev" i get error

### ISSUE THREAD

**Issue by nob345** [JadlionHD/GrowServer#9]
```
> growserver@2.3.1 dev
> rimraf dist && rimraf assets/cache && biome lint ./src && swc ./src -d dist && node -r dotenv/config dist/src/app.js

The Biome CLI package doesn't ship with prebuilt binaries for your platform yet. You can still use the CLI by cloning the biome/tools repo from GitHub, and follow the instructions there to build the CLI for your platform.
```

**Comment by JadlionHD** [comment]
Hello!
Can you tell more details about what OS & Arch did you use? it seems biomejs doesnt support it.

**Comment by nob345** [comment]
aarch64-linux-android and I use Termux

**Comment by JadlionHD** [comment]
Yeah, biomejs not support android platform.
i just updated the repo recently so try this instead
```
npm run dev:nolint
```

**Comment by nob345** [comment]
I got error when i type that code

```
> growserver@2.3.1 dev:nolint
> rimraf dist && rimraf assets/cache && swc ./src -d dist && node -r dotenv/config dist/src/app.js

Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Fallback bindings does not support filesystem access.
Failed to compile 58 files with swc.
Error: Failed to compile:
src/app.ts
src/abstracts/Action.ts
src/abstracts/Command.ts
src/abstracts/Dialog.ts
src/abstracts/Listener.ts
src/actions/DialogReturn.ts
src/actions/Drop.ts
src/actions/EnterGame.ts
src/actions/Input.ts
src/actions/JoinRequest.ts
src/actions/Quit.ts
src/actions/QuitToExit.ts
src/actions/RefreshItemData.ts
src/actions/Respawn.ts
src/actions/RespawnSpike.ts
src/actions/Trash.ts
src/actions/Wrench.ts
src/commands/Find.ts
src/commands/GiveGems.ts
src/commands/Help.ts
src/database/db.ts
src/dialogs/AreaLockEdit.ts
src/dialogs/DoorEdit.ts
src/dialogs/DropEnd.ts
src/dialogs/FindItem.ts
src/dialogs/FindItemEnd.ts
src/dialogs/RegisterEnd.ts
src/dialogs/SignEdit.ts
src/dialogs/TrashEnd.ts
src/events/Connect.ts
src/events/Disconnect.ts
src/events/Raw.ts
src/structures/BaseServer.ts
src/structures/Collection.ts
src/structures/FloodFill.ts
src/structures/Logger.ts
src/structures/Peer.ts
src/structures/Tile.ts
src/structures/Webserver.ts
src/structures/World.ts
src/tanks/Place.ts
src/tanks/Punch.ts
src/tanks/Wrench.ts
src/types/action.d.ts
src/types/base.d.ts
src/types/command.d.ts
src/types/database.d.ts
src/types/dialog.d.ts
src/types/events.d.ts
src/types/peer.d.ts
src/types/world.d.ts
src/utils/Constants.ts
src/utils/Utils.ts
src/utils/builders/DialogBuilder.ts
src/utils/enums/DataTypes.ts
src/utils/enums/ItemTypes.ts
src/utils/enums/TankTypes.ts
src/utils/enums/Tiles.ts
    at initialCompilation (/data/data/com.termux/files/home/GrowServer/node_modules/@swc/cli/lib/swc/dir.js:142:19)
    at async dir (/data/data/com.termux/files/home/GrowServer/node_modules/@swc/cli/lib/swc/dir.js:212:5)
```

**Comment by nob345** [comment]
I solved this error in Termux by installing Debian Linux, but now my device does not allow me to open localhost on port 80, and even though I change the port to 8080 in the Webserver.js file, the error is not fixed and even if I save it, the file returns to its previous state. I hope I explained my problem. Now I will throw the error code. Please help, it has always been my dream to open a private server.

```
node:events:497
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES: permission denied 0.0.0.0:80
    at Server.setupListenHandle [as _listen2] (node:net:1876:21)
    at listenInCluster (node:net:1941:12)
    at Server.listen (node:net:2029:7)
    at WebServer (/root/GrowServer/dist/src/structures/Webserver.js:67:20)
    at async /root/GrowServer/dist/src/structures/BaseServer.js:98:13
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1920:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EACCES',
  errno: -13,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 80
}
```

Version: Node.js v21.6.1

**Comment by JadlionHD** [comment]
I havent try make a server on android before, but you can try this
https://www.youtube.com/watch?v=GRho3wUTuKY
forwarding port 8080 to 80

**Comment by nob345** [comment]
Where is the port file

**Comment by nob345** [comment]
I fixed the error! But now how do I connect to it from Android?

**Comment by JadlionHD** [comment]
try to connect? using like virtualhost, powertunnel, etc

**Comment by nob345** [comment]
I can connecnt but store is not work
